### ISSUE TITLE
审核不过

### ISSUE THREAD

**Issue by FSilence** [xiaosongread/minggedou#2]
哈哈 我也是山西出来的穷孩子  缘分啊。。
我个人也开发了一个微信小程序，是通过扫描解析github pages来做的， 但是我的审核不过，提示

(1):服务涉及笔记内容，属于个人小程序未开放类目

我再微信上搜索 博客 看到了您的小程序，您也是个人开发 
请问下 您没有碰到这个问题吗？

**Comment by xiaosongread** [comment]
long time
